/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppInvoicesRouteImport } from './routes/_app/invoices'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppInventoryIndexRouteImport } from './routes/_app/inventory.index'
import { Route as AppInventoryIdRouteImport } from './routes/_app/inventory.$id'
import { Route as AppInventoryNewRouteImport } from './routes/_app/inventory.new'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app/invoices.index'
import { Route as AppInvoicesIdRouteImport } from './routes/_app/invoices.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAuthGetSessionRouteImport } from './routes/api/auth/get-session'
import { Route as ApiAuthOkRouteImport } from './routes/api/auth/ok'
import { Route as ApiAuthSignOutRouteImport } from './routes/api/auth/sign-out'
import { Route as ApiAuthSignInEmailRouteImport } from './routes/api/auth/sign-in/email'
import { Route as ApiAuthSignUpEmailRouteImport } from './routes/api/auth/sign-up/email'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryIdRoute = AppInventoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryNewRoute = AppInventoryNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInvoicesRoute,
} as any)
const AppInvoicesIdRoute = AppInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInvoicesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGetSessionRoute = ApiAuthGetSessionRouteImport.update({
  id: '/api/auth/get-session',
  path: '/api/auth/get-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthOkRoute = ApiAuthOkRouteImport.update({
  id: '/api/auth/ok',
  path: '/api/auth/ok',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignOutRoute = ApiAuthSignOutRouteImport.update({
  id: '/api/auth/sign-out',
  path: '/api/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInEmailRoute = ApiAuthSignInEmailRouteImport.update({
  id: '/api/auth/sign-in/email',
  path: '/api/auth/sign-in/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignUpEmailRoute = ApiAuthSignUpEmailRouteImport.update({
  id: '/api/auth/sign-up/email',
  path: '/api/auth/sign-up/email',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/billing': typeof AppBillingRoute
  '/inventory': typeof AppInventoryRouteWithChildren
  '/invoices': typeof AppInvoicesRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/inventory/$id': typeof AppInventoryIdRoute
  '/inventory/new': typeof AppInventoryNewRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/get-session': typeof ApiAuthGetSessionRoute
  '/api/auth/ok': typeof ApiAuthOkRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/api/auth/sign-in/email': typeof ApiAuthSignInEmailRoute
  '/api/auth/sign-up/email': typeof ApiAuthSignUpEmailRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/billing': typeof AppBillingRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/inventory/$id': typeof AppInventoryIdRoute
  '/inventory/new': typeof AppInventoryNewRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/get-session': typeof ApiAuthGetSessionRoute
  '/api/auth/ok': typeof ApiAuthOkRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/api/auth/sign-in/email': typeof ApiAuthSignInEmailRoute
  '/api/auth/sign-up/email': typeof ApiAuthSignUpEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/inventory': typeof AppInventoryRouteWithChildren
  '/_app/invoices': typeof AppInvoicesRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/inventory/$id': typeof AppInventoryIdRoute
  '/_app/inventory/new': typeof AppInventoryNewRoute
  '/_app/invoices/$id': typeof AppInvoicesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/get-session': typeof ApiAuthGetSessionRoute
  '/api/auth/ok': typeof ApiAuthOkRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/api/auth/sign-in/email': typeof ApiAuthSignInEmailRoute
  '/api/auth/sign-up/email': typeof ApiAuthSignUpEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/billing'
    | '/inventory'
    | '/invoices'
    | '/settings'
    | '/inventory/$id'
    | '/inventory/new'
    | '/invoices/$id'
    | '/api/auth/$'
    | '/api/auth/get-session'
    | '/api/auth/ok'
    | '/api/auth/sign-out'
    | '/inventory/'
    | '/invoices/'
    | '/api/auth/sign-in/email'
    | '/api/auth/sign-up/email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/billing'
    | '/settings'
    | '/'
    | '/inventory/$id'
    | '/inventory/new'
    | '/invoices/$id'
    | '/api/auth/$'
    | '/api/auth/get-session'
    | '/api/auth/ok'
    | '/api/auth/sign-out'
    | '/inventory'
    | '/invoices'
    | '/api/auth/sign-in/email'
    | '/api/auth/sign-up/email'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/billing'
    | '/_app/inventory'
    | '/_app/invoices'
    | '/_app/settings'
    | '/_app/'
    | '/_app/inventory/$id'
    | '/_app/inventory/new'
    | '/_app/invoices/$id'
    | '/api/auth/$'
    | '/api/auth/get-session'
    | '/api/auth/ok'
    | '/api/auth/sign-out'
    | '/_app/inventory/'
    | '/_app/invoices/'
    | '/api/auth/sign-in/email'
    | '/api/auth/sign-up/email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthGetSessionRoute: typeof ApiAuthGetSessionRoute
  ApiAuthOkRoute: typeof ApiAuthOkRoute
  ApiAuthSignOutRoute: typeof ApiAuthSignOutRoute
  ApiAuthSignInEmailRoute: typeof ApiAuthSignInEmailRoute
  ApiAuthSignUpEmailRoute: typeof ApiAuthSignUpEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/$id': {
      id: '/_app/inventory/$id'
      path: '/$id'
      fullPath: '/inventory/$id'
      preLoaderRoute: typeof AppInventoryIdRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/new': {
      id: '/_app/inventory/new'
      path: '/new'
      fullPath: '/inventory/new'
      preLoaderRoute: typeof AppInventoryNewRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppInvoicesRoute
    }
    '/_app/invoices/$id': {
      id: '/_app/invoices/$id'
      path: '/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AppInvoicesIdRouteImport
      parentRoute: typeof AppInvoicesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/get-session': {
      id: '/api/auth/get-session'
      path: '/api/auth/get-session'
      fullPath: '/api/auth/get-session'
      preLoaderRoute: typeof ApiAuthGetSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/ok': {
      id: '/api/auth/ok'
      path: '/api/auth/ok'
      fullPath: '/api/auth/ok'
      preLoaderRoute: typeof ApiAuthOkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-out': {
      id: '/api/auth/sign-out'
      path: '/api/auth/sign-out'
      fullPath: '/api/auth/sign-out'
      preLoaderRoute: typeof ApiAuthSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in/email': {
      id: '/api/auth/sign-in/email'
      path: '/api/auth/sign-in/email'
      fullPath: '/api/auth/sign-in/email'
      preLoaderRoute: typeof ApiAuthSignInEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-up/email': {
      id: '/api/auth/sign-up/email'
      path: '/api/auth/sign-up/email'
      fullPath: '/api/auth/sign-up/email'
      preLoaderRoute: typeof ApiAuthSignUpEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppInventoryRouteChildren {
  AppInventoryIdRoute: typeof AppInventoryIdRoute
  AppInventoryNewRoute: typeof AppInventoryNewRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
}

const AppInventoryRouteChildren: AppInventoryRouteChildren = {
  AppInventoryIdRoute: AppInventoryIdRoute,
  AppInventoryNewRoute: AppInventoryNewRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
}

const AppInventoryRouteWithChildren = AppInventoryRoute._addFileChildren(
  AppInventoryRouteChildren,
)

interface AppInvoicesRouteChildren {
  AppInvoicesIdRoute: typeof AppInvoicesIdRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
}

const AppInvoicesRouteChildren: AppInvoicesRouteChildren = {
  AppInvoicesIdRoute: AppInvoicesIdRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
}

const AppInvoicesRouteWithChildren = AppInvoicesRoute._addFileChildren(
  AppInvoicesRouteChildren,
)

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppInventoryRoute: typeof AppInventoryRouteWithChildren
  AppInvoicesRoute: typeof AppInvoicesRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppInventoryRoute: AppInventoryRouteWithChildren,
  AppInvoicesRoute: AppInvoicesRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthGetSessionRoute: ApiAuthGetSessionRoute,
  ApiAuthOkRoute: ApiAuthOkRoute,
  ApiAuthSignOutRoute: ApiAuthSignOutRoute,
  ApiAuthSignInEmailRoute: ApiAuthSignInEmailRoute,
  ApiAuthSignUpEmailRoute: ApiAuthSignUpEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
