/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppInvoicesRouteImport } from './routes/_app/invoices'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppInventoryIdRouteImport } from './routes/_app/inventory.$id'
import { Route as AppInventoryIndexRouteImport } from './routes/_app/inventory.index'
import { Route as AppInventoryNewRouteImport } from './routes/_app/inventory.new'
import { Route as AppInvoicesIdRouteImport } from './routes/_app/invoices.$id'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app/invoices.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryIdRoute = AppInventoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryNewRoute = AppInventoryNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInvoicesIdRoute = AppInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInvoicesRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInvoicesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/billing': typeof AppBillingRoute
  '/inventory': typeof AppInventoryRouteWithChildren
  '/invoices': typeof AppInvoicesRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/inventory/$id': typeof AppInventoryIdRoute
  '/inventory/new': typeof AppInventoryNewRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/billing': typeof AppBillingRoute
  '/inventory': typeof AppInventoryRouteWithChildren
  '/invoices': typeof AppInvoicesRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/inventory/$id': typeof AppInventoryIdRoute
  '/inventory/new': typeof AppInventoryNewRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/inventory': typeof AppInventoryRouteWithChildren
  '/_app/invoices': typeof AppInvoicesRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/inventory/$id': typeof AppInventoryIdRoute
  '/_app/inventory/new': typeof AppInventoryNewRoute
  '/_app/invoices/$id': typeof AppInvoicesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/billing'
    | '/inventory'
    | '/invoices'
    | '/settings'
    | '/inventory/$id'
    | '/inventory/new'
    | '/invoices/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/billing'
    | '/inventory'
    | '/invoices'
    | '/settings'
    | '/'
    | '/inventory/$id'
    | '/inventory/new'
    | '/invoices/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/billing'
    | '/_app/inventory'
    | '/_app/invoices'
    | '/_app/settings'
    | '/_app/'
    | '/_app/inventory/$id'
    | '/_app/inventory/new'
    | '/_app/invoices/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/$id': {
      id: '/_app/inventory/$id'
      path: '/$id'
      fullPath: '/inventory/$id'
      preLoaderRoute: typeof AppInventoryIdRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/new': {
      id: '/_app/inventory/new'
      path: '/new'
      fullPath: '/inventory/new'
      preLoaderRoute: typeof AppInventoryNewRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppInvoicesRoute
    }
    '/_app/invoices/$id': {
      id: '/_app/invoices/$id'
      path: '/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AppInvoicesIdRouteImport
      parentRoute: typeof AppInvoicesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppInventoryRouteChildren {
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
  AppInventoryIdRoute: typeof AppInventoryIdRoute
  AppInventoryNewRoute: typeof AppInventoryNewRoute
}

const AppInventoryRouteChildren: AppInventoryRouteChildren = {
  AppInventoryIndexRoute: AppInventoryIndexRoute,
  AppInventoryIdRoute: AppInventoryIdRoute,
  AppInventoryNewRoute: AppInventoryNewRoute,
}

const AppInventoryRouteWithChildren = AppInventoryRoute._addFileChildren(
  AppInventoryRouteChildren,
)

interface AppInvoicesRouteChildren {
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppInvoicesIdRoute: typeof AppInvoicesIdRoute
}

const AppInvoicesRouteChildren: AppInvoicesRouteChildren = {
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppInvoicesIdRoute: AppInvoicesIdRoute,
}

const AppInvoicesRouteWithChildren = AppInvoicesRoute._addFileChildren(
  AppInvoicesRouteChildren,
)

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppInventoryRoute: typeof AppInventoryRouteWithChildren
  AppInvoicesRoute: typeof AppInvoicesRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppInventoryRoute: AppInventoryRouteWithChildren,
  AppInvoicesRoute: AppInvoicesRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
